export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
export const NOTIFICATION_PREFERENCE_REPOSITORY =
  'NOTIFICATION_PREFERENCE_REPOSITORY';
export const EMAIL_NOTIFICATION_CHANNEL = 'EMAIL_NOTIFICATION_CHANNEL';
export const IN_APP_NOTIFICATION_CHANNEL = 'IN_APP_NOTIFICATION_CHANNEL';
